export const thirdImage =
  "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Dominos_pizza_logo.svg/200px-Dominos_pizza_logo.svg.png";
export const ResList = [
  {
    id: 1,
    name: "Burger King",
    cuisine: "American",
    rating: 4.2,
    deliveryTime: "30 mins",
    image: thirdImage,
  },
  {
    id: 2,
    name: "Pizza Hut",
    cuisine: "Italian",
    rating: 3.8,
    deliveryTime: "35 mins",
    image: thirdImage,
  },
  {
    id: 3,
    name: "Domino's Pizza",
    cuisine: "Italian",
    rating: 3.1,
    deliveryTime: "32 mins",
    image: thirdImage,
  },
  {
    id: 4,
    name: "KFC",
    cuisine: "American",
    rating: 3.3,
    deliveryTime: "28 mins",
    image: thirdImage,
  },
  {
    id: 5,
    name: "Subway",
    cuisine: "Healthy",
    rating: 4.0,
    deliveryTime: "25 mins",
    image: thirdImage,
  },
  {
    id: 6,
    name: "McDonald's",
    cuisine: "American",
    rating: 4.2,
    deliveryTime: "27 mins",
    image: thirdImage,
  },
  {
    id: 7,
    name: "Biryani Blues",
    cuisine: "Indian",
    rating: 4.4,
    deliveryTime: "40 mins",
    image: thirdImage,
  },
  {
    id: 8,
    name: "Haldiram's",
    cuisine: "Indian",
    rating: 4.3,
    deliveryTime: "33 mins",
    image: thirdImage,
  },
  {
    id: 9,
    name: "Faasos",
    cuisine: "Wraps & Rolls",
    rating: 4.1,
    deliveryTime: "29 mins",
    image: thirdImage,
  },
  {
    id: 10,
    name: "Behrouz Biryani",
    cuisine: "Biryani",
    rating: 4.5,
    deliveryTime: "38 mins",
    image: thirdImage,
  },
];
